version: "3"

services:
  tomcat:
    build: ../tomcat
    restart: on-failure
    volumes:
      - ./target/${PROJECT_NAME?}.war:/usr/local/tomcat/webapps/${PROJECT_NAME?}.war
    ports:
      - 8888:8080
    links:
      - "postgres:db"

  postgres:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
  
volumes:
    postgres:
