version: "3"

services:
  tomcat:
    build: ../tomcat
    restart: on-failure
    env_file: .env
    volumes:
      - ./target/${PROJECT_NAME?}.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - 8888:8080
    links:
      - postgres

  flyway:
    image: flyway/flyway
    env_file: .env
    command: -url=${DATABASE_URL?} -schemas=public -user=${DATABASE_USERNAME?} -password=${DATABASE_PASSWORD?} -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    links:
      - postgres

  postgres:
    image: postgres:13
    restart: on-failure
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME?}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD?}
      PGDATA: /data/postgres
    command: postgres -c shared_preload_libraries=pg_stat_statements -c log_statement=all -c pg_stat_statements.track=all -c max_connections=200
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
  
volumes:
    postgres:
