version: "3"

services:
  tomcat:
    build: ./tomcat
    volumes:
      - ./target/${COMPOSE_PROJECT_NAME}:/home/linuxbrew/.linuxbrew/opt/tomcat/libexec/webapps/${COMPOSE_PROJECT_NAME}
    ports:
      - 8888:8080
